# Personal Information Configuration
# 个人信息配置文件

# Basic Information | 基本信息
basic_info:
  first_name: "Jiajun"  # 名字
  last_name: "Huo"   # 姓氏
  email: "jiajunhuo@gmail.com"       # 邮箱
  phone: "+1 2677778518"       # 电话号码 (格式: +1 (xxx) xxx-xxxx)
  
# Location | 地址信息
location:
  address: "904 West Stoughton"     # 街道地址
  city: "Urbana"        # 城市
  state: "IL"       # 州/省
  zipcode: "61801"     # 邮编
  country: "United States"     # 国家
  
# Professional Links | 专业链接
professional:
  linkedin: "https://www.linkedin.com/in/nickhuo/"    # LinkedIn URL (https://www.linkedin.com/in/xxx)
  portfolio: "nickhuo.com"   # 个人网站/作品集
  github: "https://github.com/NickHuo"      # GitHub URL (https://github.com/xxx)
  
# Education | 教育背景
education:
  university: "University of Illinois at Urbana-Champaign"  # 大学名称
  degree: "Master of Science"      # 学位 (e.g., Bachelor of Science, Master of Science)
  major: "Information Science"       # 专业
  graduation_year: "2026"  # 毕业年份
  gpa: "3.9"         # GPA (可选)
  
# Work Experience | 工作经验
work:
  current_company: ""   # 当前公司
  current_title: ""     # 当前职位
  years_experience: ""  # 工作年限
  
# Application Details | 申请详情
application:
  salary_expectation: "100000"     # 期望薪资
  work_authorization: "Yes"     # 工作许可 (Yes/No)
  require_sponsorship: "No"    # 是否需要签证赞助 (Yes/No)
  start_date: "Immediately"            # 可以开始工作的时间 (e.g., "2 weeks", "Immediately")
  referral: "None"              # 推荐人/来源
  

  
# Diversity Information | 多样性信息 (通常可选)
diversity:
  gender: "Prefer not to say"      # 性别
  race: "Prefer not to say"        # 种族
  veteran_status: "I am not a veteran"  # 退伍军人状态
  disability_status: "Prefer not to say"  # 残疾状态
  
# Resume | 简历
resume:
  file_path: "/Users/nickhuo/Documents/GitHub/semi-apply/data/JiajunHuo_SWE_UIUC.pdf"  # 简历文件路径 (PDF格式)
  
# Additional Information | 其他信息
additional:
  # 可以在这里添加任何其他可能需要的字段
  pronouns: "He/Him"  # 代词 (可选)
  website: "nickhuo.com"   # 其他网站 (可选)
  publications: []  # 出版物列表 (可选)

